wandb_version: 1

lr:
  desc: null
  value: 5.0e-05
batch_size:
  desc: null
  value: 4
data_path:
  desc: null
  value: ./workdir
epochs:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1723291296
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.6
      8:
      - 2
      - 5
      13: linux-x86_64
